### PR TITLE
Add ELM327Plugin

### PR DESCRIPTION
**Pull request by ardera**
ELM327Plugin is a plugin for communicating with an ELM327, i.e. querying and listening to OBD data (vehicle speed, rpm, coolant temp, engine load, ...).
I'm gonna publish the code for the flutter-side of that plugin soon.
The plugin is currently able to query the ELM about 20-25 times a second, which should be enough for (almost) live vehicle data visualization.

Also, some small reworks in the main flutter-pi file.

### CODE REVIEW

**Comment by Ravish1** [comment]
Hey Andrea have you published the code Elm 327 plugin.Please Revert.

**Comment by Ravish1** [comment]
Is there any way to reach out to you? I have to ask something regarding Flutter OBD .

**Comment by ardera** [comment]
Hey, I used it for a personal project, not sure I have the dart source lying around somewhere.

Though it should be pretty easy to build your own ELM327 package on top of my [`linux_serial`](https://pub.dev/packages/linux_serial) plugin, the communication is very simple

**Comment by Ravish1** [comment]
Hey @ardera  thanks man I am checking. Actually I am on deadline of my project so need urgent ,can you once recheck the plugin code may be you find , even I can pay for the source code. Thank you so much.

**Comment by Ravish1** [comment]
@ardera  The main issue is I have recently switched to flutter from Android development, so not have used with flutter. It would be really great if you provide the code or any other example link

**Comment by Ravish1** [comment]
@ardera Can you please also check your gmail.

**Comment by ardera** [comment]
Here you go:
[elm327.zip](https://github.com/ardera/flutter-pi/files/8223715/elm327.zip)

There's one version based on the ELM327 plugin (that was introduced in this PR and later removed) and one version based on `linux_serial`. The latter is the newer one, though not sure I finished it

(Btw those are both pretty old so not null-safe)

**Comment by Ravish1** [comment]
Hey @ardera I have mailed you on your email id from rsss007008@gmail.com ,please check once you get time.I want to develop a app in flutter for OBD with no interface just a bluetooth screen and OBD data that's it .Can you please get back to me if you are interested we can discuss time and budget if you are interested .Please revert

**Pull request merged**
