### PR TITLE
Implement AOT

### PR DESCRIPTION
**Pull request by DisDis**

### CODE REVIEW

**Comment by ardera** [comment]
Thanks for your contribution @DisDis !
I'll actually merge my own version of AOT support (plus some refactors, fixes, additions) soon
I'll merge this PR anywa so people can enjoy AOT in the meantime

**Comment by GioPan04** [comment]
So, now how we can try the AOT mode?

**Comment by DisDis** [comment]
> So, now how we can try the AOT mode?
1.Build release engine(only dev channel, currently)
2.Instruction for libapp.so:  https://github.com/ardera/flutter-pi/issues/65#issuecomment-666703389
3. flutter-pi -a ./libapp.so ./assets

**Comment by GioPan04** [comment]
> > So, now how we can try the AOT mode?
> 
> 1.Build release engine(only dev channel, currently)
> 2.Instruction for libapp.so: [#65 (comment)](https://github.com/ardera/flutter-pi/issues/65#issuecomment-666703389)
> 3. flutter-pi -a ./libapp.so ./assets

How can I build the release engine? Can you link me a doc or something? The only doc I found is this:  [https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-macos-or-linux](url)

**Comment by GioPan04** [comment]
Okay jk, i found your comment where you explain how to build the engine [https://github.com/ardera/flutter-pi/issues/65#issuecomment-665694767](url)

**Comment by ardera** [comment]
@DisDis I just realized, since you're using the dev channel anyway, you can just rely on [`FlutterEngineCreateAOTData`](https://github.com/flutter/engine/blob/460039e0e086e4c3d889738abda21ec7106b9e64/shell/platform/embedder/embedder.h#L1030) and [`FlutterEngineCollectAOTData`](https://github.com/flutter/engine/blob/460039e0e086e4c3d889738abda21ec7106b9e64/shell/platform/embedder/embedder.h#L1048) to load and destroy the AOT data, instead of doing it manually

**Comment by DisDis** [comment]
@ardera 
What are these methods used for?
I have not researched flutter in this direction.

**Comment by ardera** [comment]
You invoke `FlutterEngineCreateAOTData` with the path to the `libapp.so` and it does all the loading for you
These API calls are not present on the release channel, though

**Pull request merged**
