### PR TITLE
reimplement legacy modesetting

### PR DESCRIPTION
**Pull request by ardera**
This is pretty ugly right now, and I'm not sure the performance is as good as with atomic modesetting

### CODE REVIEW

**Comment by bing-mao** [comment]
Thank you ardera, I have checkout this branch and test on my board.

It says:

root@nanopi3:~/flutter-pi# ./out/flutter-pi ../flutter_assets/
[modesetting] Could not set DRM client atomic capable. drmSetClientCap: Operation not supported
[flutter-pi] Could not create drmdev from device at "/dev/dri/card1". Continuing.
[modesetting] Could not set DRM client universal planes capable. drmSetClientCap: Operation not supported
[flutter-pi] Could not create drmdev from device at "/dev/dri/card0". Continuing.
flutter-pi couldn't find a usable DRM device.
Please make sure you've enabled the Fake-KMS driver in raspi-config.
If you're not using a Raspberry Pi, please make sure there's KMS support for your graphics chip.

**Comment by ardera** [comment]
Should work now and performance should be acceptable

**Comment by bing-mao** [comment]
Thank you ardera!

I tested your latest code, Looks the app read incorrect screen info.

===================================
display mode:
  resolution: 1021 x 61440
  refresh rate: 4026532341Hz
  physical size: 108mm x 64mm
  flutter device pixel ratio: 2.487817
===================================
 then it gets error when allocating memory

DRM_IOCTL_MODE_CREATE_DUMB failed: Cannot allocate memory

I will post the log file into the CR

Thanks,
Bing

**Comment by ardera** [comment]
Okay, I understand where the incorrect refresh rate may come from. But I have no idea why the resolution is wrong. I added some logging, can you try it out and send me the output?

**Comment by bing-mao** [comment]
Hi ardera,
Here is the log file. Looks the resolution is still very large.

[nanopi3_flutter-pi_log2.txt](https://github.com/ardera/flutter-pi/files/5365837/nanopi3_flutter-pi_log2.txt)

**Comment by ardera** [comment]
Okay, can you try again with this commit? I fixed one thing that could've been the cause

**Comment by bing-mao** [comment]
HI ardera,
Thank you for quick response! Now the build is good, no crash and the touch is working well. Here is the starting log
[nanopi3_flutter-pi_log3.txt](https://github.com/ardera/flutter-pi/files/5368684/nanopi3_flutter-pi_log3.txt)

Though my device has some issue when displaying complicated UI, looks like something didn't redraw, but this existed on the older build as well. Overall, your latest code is better in every aspect compared with the old commit I used.

BR,
Bing

**Comment by ardera** [comment]
That's probably a driver issue. There are a lot of driver issues with these niche GPUs. Driver issues is actually where this project started, the original chinmaygarde/flutter_from_scratch project used the legacy OpenGL driver on the Raspberry Pi, which was completely unusable. (A lot of textures disappearing and reappearing) So I switched it over to using DRM/KMS and Mesa

**Comment by bing-mao** [comment]
Thank you ardera. Appreciate you generous help. I will check my driver.

**Comment by ardera** [comment]
Thanks, I'm glad I could help!

**Pull request merged**
